# Generated by Django 4.0.5 on 2022-07-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("_message_data", models.TextField()),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Deferred"), (10, "Low"), (20, "Medium"), (30, "High")], default=20
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("result", models.PositiveSmallIntegerField(choices=[(0, "Success"), (1, "Failure")])),
                ("log_message", models.TextField()),
            ],
        ),
    ]
