# Generated by Django 4.0.7 on 2022-09-05 18:42

from django.db import migrations, models

import mailer.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message_data", models.TextField()),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Deferred"), (10, "Low"), (20, "Medium"), (30, "High")], default=20
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(mailer.models.MessageDataPropertiesMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_data", models.TextField()),
                ("when_added", models.DateTimeField(db_index=True)),
                ("when_attempted", models.DateTimeField(auto_now_add=True)),
                ("result", models.PositiveSmallIntegerField(choices=[(0, "Success"), (1, "Failure")])),
                ("log_message", models.TextField()),
            ],
            bases=(mailer.models.MessageDataPropertiesMixin, models.Model),
        ),
    ]
