# Generated by Django 4.0.7 on 2022-09-14 21:43

from django.db import migrations, models

import nitrorss.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_email_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[nitrorss.common.validators.DisposableEmailBlacklistValidator()],
                verbose_name="email address",
            ),
        ),
    ]
