version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: server
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

  qcluster:
    build: .
    command: qcluster
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres

volumes:
  postgres_data:
