app = "nitrorss"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  DJANGO_ALLOWED_HOSTS = "localhost,127.0.0.1,nitrorss.fly.dev,nitrorss.com"
  DJANGO_CSRF_TRUSTED_ORIGINS = "https://nitrorss.fly.dev,https://nitrorss.com"
  DJANGO_DEBUG = false

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  web = "server"
  worker = "qcluster"

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 3
    timeout = "2s"
