# Generated by Django 4.0.5 on 2022-07-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(db_index=True, max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("last_check", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(max_length=500)),
                ("date_published", models.DateTimeField()),
                ("authors", models.CharField(blank=True, max_length=255)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entries", to="feeds.feed"
                    ),
                ),
            ],
            options={
                "verbose_name": "feed entry",
                "verbose_name_plural": "feed entries",
            },
        ),
        migrations.CreateModel(
            name="FeedConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(db_index=True, max_length=255)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="connections", to="feeds.feed"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="feedconnection",
            constraint=models.UniqueConstraint(fields=("feed", "url"), name="unique_feed_connection_url"),
        ),
    ]
