# Generated by Django 4.0.5 on 2022-06-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="url",
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
