# Generated by Django 4.0.5 on 2022-06-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0002_alter_feed_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=255)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="connections", to="feeds.feed"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="feedconnection",
            constraint=models.UniqueConstraint(fields=("feed", "url"), name="unique_feed_connection_url"),
        ),
    ]
