# Generated by Django 4.0.5 on 2022-06-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feeds", "0003_feedconnection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="url",
            field=models.URLField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="feedconnection",
            name="url",
            field=models.URLField(db_index=True, max_length=255),
        ),
    ]
