# Generated by Django 4.0.7 on 2022-09-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
