# Generated by Django 4.0.7 on 2022-09-14 16:41

from django.db import migrations, models

import subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_confirmed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="subscription",
            name="unsubscribe_token",
            field=models.CharField(default=subscriptions.models.get_unsubscribe_token, max_length=64, unique=True),
        ),
    ]
