# Generated by Django 4.0.5 on 2022-06-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="schedule",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Realtime"),
                    (2, "Every 2 Hours"),
                    (3, "Every 4 Hours"),
                    (4, "Every 6 Hours"),
                    (5, "Every 12 Hours"),
                    (6, "Daily"),
                ],
                default=6,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(fields=("feed", "target_email"), name="unique_subscription_email"),
        ),
    ]
