# Generated by Django 4.0.7 on 2022-09-14 21:43

from django.db import migrations, models

import nitrorss.common.validators


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_remove_subscription_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="target_email",
            field=models.EmailField(
                max_length=254, validators=[nitrorss.common.validators.DisposableEmailBlacklistValidator()]
            ),
        ),
    ]
