# Generated by Django 4.1.2 on 2022-10-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_alter_subscription_target_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="last_notification",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
