name: Tests
on: [push]

jobs:
  unittests:
    name: Django Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        env:
          BASE_URL: http://example.com
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:${{ matrix.db_port }}/${{ matrix.db }}
        run: |
          python manage.py collectstatic --noinput
          python manage.py compress
          python manage.py test
